language: emacs-lisp
sudo: false

env:
  - EVM_EMACS=emacs-26.1-travis
  - EVM_EMACS=emacs-26.2-travis
  - EVM_EMACS=emacs-git-snapshot-travis

matrix:
  fast_finish: true
  allow_failures:
    env:
      - EVM_EMACS=emacs-git-snapshot-travis

before_script:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip

script:
  - lsb_release -a
  - ${EMACS:=emacs} --version
  - ./.travis/test-startup.sh
